### PR TITLE
add azure subscription

### PR DESCRIPTION
**Pull request by sei-ebram**
Adds a command to help facilitate switching subscriptions, or list of subscriptions available if no `subscription name` is provided.

Usage:  `azs <subscription>`.

**note**: allows space in subscription names without using quotes, for example: `azs test subscription`.

### CODE REVIEW

**Comment by sei-ebram** [comment]
@sei-jmattson might be helpful for this command to execute `aksme` directly after..not sure how you feel about that since `aksme` has those other optional args.  But it will need to be run to "switch subscriptions" in the simple sense

**Comment by sei-jmattson** [comment]
Can't believe I didn't see this until now!  Got to fix my notifications!  
Cool.  You want to append to the Readme usage?

**Comment by sei-ebram** [comment]
@sei-jmattson let me know if that's good!

**Comment by ebram-va** [comment]
@sei-jmattson do you want to merge this in?

**Pull request merged**
